jobs:
- job: 'release_aks'
  displayName: 'Release aks'
  steps:
  - task: Kubernetes@1
    displayName: 'kubectl login'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'sp-jorge'
      azureResourceGroup: 'resource-group-jorge-regino'
      kubernetesCluster: 'aksjorge'
      useClusterAdmin: true
      namespace: 'namespace-jorge'
      command: 'login' 
  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'sp-jorge'
      azureResourceGroup: 'resource-group-jorge-regino'
      kubernetesCluster: 'aksjorge'
      namespace: 'namespace-jorge'
      command: 'apply'
      arguments: '-f $(System.DefaultWorkingDirectory)/templates/deployment.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'
      azureSubscriptionEndpointForSecrets: 'sp-jorge'
      azureContainerRegistry: 'acrjorge.azurecr.io'
      secretName: 'mysecretk'
  - script: |
      sleep 120
      kubectl get pod -n $(namespace)
  - task: CmdLine@2
    displayName: Check External IP
    inputs:
      script: bash -c 'external_ip=""; while [ -z $external_ip ]; do echo "Waiting for end point..."; external_ip=$(kubectl get svc $(name) -n $(namespace) --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}"); [ -z "$external_ip" ] && sleep 10; done; echo "End point ready-" && echo $external_ip' 
    timeoutInMinutes: 5